name: lory
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.3
  firebase_core: ^4.1.1
  firebase_database: ^12.0.2
  firebase_auth: ^6.1.1
  google_sign_in: ^6.2.1
  cloud_firestore: ^6.0.3
  firebase_storage: ^13.0.3
  image_picker: ^1.2.0
  http: ^1.2.0
  html: ^0.15.4
  path: ^1.8.3
  path_provider: ^2.1.1
  cloudinary_public: ^0.21.0
  flutter_dotenv: ^5.1.0
  mime: ^1.0.4
  easy_localization: ^3.0.3
  url_launcher: ^6.2.2 # Để mở email, phone, browser
  cached_network_image: ^3.3.0
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/lang/
